version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expo-pokedex-app
    volumes:
      - ".:/app"
    env_file:
      - ".env"
    ports:
      - "9006:19006"
    tty: true